sudo: required
language: python
python:
- '3.4'
- '3.5'
- '3.6'
#- '3.7'
notifications:
  email: false
#addons:
#  apt:
#    sources:
#      - deadsnakes
#    packages:
#      - python3.7
install:
- pip install coveralls
script:
  - python setup.py test
  - coverage run --source=genomerator setup.py test
# after_success: coveralls
# deploy:
  # provider: pypi
  # user:
  # password:
    # secure: #
  # on:
    # tags: true
    # branch: master
